require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('--- SEEDING COLORIDO 2K26 DATABASE ---');

  // Clean tables in reverse dependency order
  await prisma.contactMessage.deleteMany({});
  await prisma.result.deleteMany({});
  await prisma.schedule.deleteMany({});
  await prisma.registration.deleteMany({});
  await prisma.event.deleteMany({});
  await prisma.admin.deleteMany({});
  // As per Section 17: "Do not create fake normal users."
  // Users will sign up via Google OAuth or create account.

  // 1. SEED ADMIN
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@colorido2k26.com';
  const rawAdminPassword = process.env.ADMIN_DEFAULT_PASSWORD || 'Admin@Colorido2026!';
  const passwordHash = await bcrypt.hash(rawAdminPassword, 10);

  const admin = await prisma.admin.create({
    data: {
      email: adminEmail,
      name: 'Festival Convenor Admin',
      passwordHash: passwordHash,
      role: 'ADMIN'
    }
  });
  console.log(`✓ Admin created: ${admin.email}`);

  // 2. SEED ALL 29 MANDATORY EVENTS (9 Sports, 10 Cultural, 10 Technical)
  const events = [
    // ==========================================
    // 9 SPORTS EVENTS (Section 21)
    // ==========================================
    {
      title: 'Cricket Championship',
      slug: 'cricket',
      category: 'SPORTS',
      visualType: 'cricket',
      description: 'The premier collegiate T20 cricket tournament of COLORIDO 2K26. Fast-paced knockout matches on turf pitches under professional floodlights with DRS and digital scoring.',
      shortDescription: 'T20 tournament played on turf wickets with white leather balls under lights.',
      rules: '1. Standard ICC T20 playing regulations apply.\n2. Squad of 11 playing + 4 subs.\n3. Matches are 15 overs per side for prelims, 20 overs for finals.\n4. Official umpire decisions are final.',
      eligibility: 'Open to bonafide college students with valid collegiate ID.',
      date: 'October 15-16, 2026',
      startTime: '08:30 AM',
      endTime: '06:00 PM',
      venue: 'Main Sports Complex Cricket Ground',
      prizePool: '₹50,000',
      firstPrize: '₹30,000 + Golden Trophy',
      secondPrize: '₹20,000 + Silver Plate',
      capacity: 32,
      registeredCount: 14,
      participantType: 'TEAM',
      minTeamSize: 11,
      maxTeamSize: 15,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?w=800&q=80'
    },
    {
      title: 'Football Champions Cup',
      slug: 'football',
      category: 'SPORTS',
      visualType: 'football',
      description: 'An electrifying 11-a-side inter-collegiate football tournament on FIFA standard natural grass pitch with certified referees and stadium cheering zones.',
      shortDescription: '11-a-side knockout tournament on FIFA standard natural turf arena.',
      rules: '1. FIFA regulations with 35-minute halves and 10-minute halftime.\n2. Direct penalty shootouts in knockout draws.\n3. Maximum 3 substitutions per match.',
      eligibility: 'Bonafide enrolled undergraduate/postgraduate college students.',
      date: 'October 15-16, 2026',
      startTime: '07:30 AM',
      endTime: '05:30 PM',
      venue: 'South Stadium Football Arena',
      prizePool: '₹40,000',
      firstPrize: '₹25,000 + Champions Cup',
      secondPrize: '₹15,000 + Runners Shield',
      capacity: 24,
      registeredCount: 10,
      participantType: 'TEAM',
      minTeamSize: 11,
      maxTeamSize: 16,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80'
    },
    {
      title: 'Basketball Showdown',
      slug: 'basketball',
      category: 'SPORTS',
      visualType: 'basketball',
      description: 'Fast-paced 5v5 full-court basketball tournament with hardwood indoor court, shot clocks, and high-flying dunks.',
      shortDescription: 'High-octane 5v5 full-court tournament under FIBA collegiate rules.',
      rules: '1. FIBA collegiate rules: 4 quarters of 8 minutes each.\n2. 24-second shot clock strictly enforced.\n3. 5 team fouls per quarter result in free throws.',
      eligibility: 'All collegiate student athletes with valid ID card.',
      date: 'October 15, 2026',
      startTime: '09:00 AM',
      endTime: '04:30 PM',
      venue: 'Indoor Sports Stadium Court 1',
      prizePool: '₹30,000',
      firstPrize: '₹20,000 + Trophy',
      secondPrize: '₹10,000 + Medals',
      capacity: 20,
      registeredCount: 8,
      participantType: 'TEAM',
      minTeamSize: 5,
      maxTeamSize: 10,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80'
    },
    {
      title: 'Volleyball Championship',
      slug: 'volleyball',
      category: 'SPORTS',
      visualType: 'volleyball',
      description: 'Competitive 6-player outdoor volleyball contest testing spikes, blocks, and stamina on pro clay courts.',
      shortDescription: 'Best of three sets collegiate volleyball championship.',
      rules: '1. Standard FIVB rules: Best of 3 sets (25 pts, final set 15 pts).\n2. Rotation and net touch rules strictly observed.',
      eligibility: 'Collegiate teams with active student status.',
      date: 'October 15-16, 2026',
      startTime: '08:00 AM',
      endTime: '04:00 PM',
      venue: 'East Campus Volleyball Courts',
      prizePool: '₹25,000',
      firstPrize: '₹15,000 + Memento',
      secondPrize: '₹10,000 + Runner Cup',
      capacity: 20,
      registeredCount: 7,
      participantType: 'TEAM',
      minTeamSize: 6,
      maxTeamSize: 9,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&q=80'
    },
    {
      title: 'Badminton Smash League',
      slug: 'badminton',
      category: 'SPORTS',
      visualType: 'badminton',
      description: 'Singles and doubles badminton matches on synthetic courts with Yonex feather shuttles.',
      shortDescription: 'Singles & Doubles knockout badminton on indoor synthetic courts.',
      rules: '1. BWF 21-point rally scoring system, best of 3 games.\n2. Non-marking indoor badminton shoes mandatory.',
      eligibility: 'Individual collegiate competitors.',
      date: 'October 16, 2026',
      startTime: '09:00 AM',
      endTime: '05:00 PM',
      venue: 'Indoor Badminton Pavilion',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Racquet Kit',
      secondPrize: '₹8,000 + Medals',
      capacity: 40,
      registeredCount: 22,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80'
    },
    {
      title: 'Grandmaster Chess Challenge',
      slug: 'chess',
      category: 'SPORTS',
      visualType: 'chess',
      description: 'FIDE rated rapid chess tournament testing strategy, tactical foresight, and endgame masterclasses with electronic DGT clocks.',
      shortDescription: 'FIDE Swiss-system rapid chess (15 min + 10s increment).',
      rules: '1. 6 rounds Swiss system pairing.\n2. Touch-move rule strictly applied.\n3. Electronic devices strictly prohibited during rounds.',
      eligibility: 'Open to all college students.',
      date: 'October 15, 2026',
      startTime: '10:00 AM',
      endTime: '05:30 PM',
      venue: 'Student Activity Center Hall A',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Grandmaster Trophy',
      secondPrize: '₹8,000 + Chess Kit',
      capacity: 64,
      registeredCount: 35,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&q=80'
    },
    {
      title: 'Kabaddi Warriors Cup',
      slug: 'kabaddi',
      category: 'SPORTS',
      visualType: 'kabaddi',
      description: 'High-intensity Pro-Kabaddi style clashes with continuous raids, bonus line contests, and thunderous super tackles on padded mats.',
      shortDescription: 'Pro-style mat kabaddi tournament with 7v7 squad matches.',
      rules: '1. AKFI standard rules on synthetic pro mats.\n2. 20-minute halves with 5-minute break.\n3. Maximum body weight limit: 80 kg.',
      eligibility: 'College teams with verified student credentials.',
      date: 'October 16, 2026',
      startTime: '08:30 AM',
      endTime: '04:30 PM',
      venue: 'Open Air Stadium Mat Arena',
      prizePool: '₹35,000',
      firstPrize: '₹22,000 + Trophy',
      secondPrize: '₹13,000 + Runners Cup',
      capacity: 16,
      registeredCount: 9,
      participantType: 'TEAM',
      minTeamSize: 7,
      maxTeamSize: 12,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&q=80'
    },
    {
      title: 'Table Tennis Open',
      slug: 'table-tennis',
      category: 'SPORTS',
      visualType: 'tabletennis',
      description: 'Lightning-fast spin, slice, and rally duels on ITTF approved Stag tables with 3-star balls.',
      shortDescription: 'Fast-paced singles & doubles table tennis tournament.',
      rules: '1. ITTF 11-point sets, best of 5 games in knockouts.\n2. 2-point serve alternation.',
      eligibility: 'Bonafide college students.',
      date: 'October 15, 2026',
      startTime: '09:30 AM',
      endTime: '04:00 PM',
      venue: 'Indoor Recreation Complex',
      prizePool: '₹18,000',
      firstPrize: '₹11,000 + Pro Paddle',
      secondPrize: '₹7,000 + Medals',
      capacity: 32,
      registeredCount: 16,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&q=80'
    },
    {
      title: 'Athletics Championship',
      slug: 'athletics',
      category: 'SPORTS',
      visualType: 'athletics',
      description: 'Track and field events including 100m, 200m, 400m sprint heats, 4x100m relay, long jump, and shot put on synthetic tracks.',
      shortDescription: 'Track & field sprints, relays, and field disciplines.',
      rules: '1. World Athletics rules apply.\n2. Running spikes allowed (maximum 6mm spikes).\n3. False start causes immediate disqualification.',
      eligibility: 'All collegiate athletes with medical clearance.',
      date: 'October 17, 2026',
      startTime: '07:00 AM',
      endTime: '01:00 PM',
      venue: 'Central Olympic Synthetic Track',
      prizePool: '₹30,000',
      firstPrize: '₹18,000 + Best Athlete Cup',
      secondPrize: '₹12,000 + Medals',
      capacity: 60,
      registeredCount: 28,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 4,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80'
    },

    // ==========================================
    // 10 CULTURAL EVENTS (Section 22)
    // ==========================================
    {
      title: 'Dance Fiesta',
      slug: 'dance',
      category: 'CULTURAL',
      visualType: 'dance',
      description: 'Mesmerizing solo, duo, and group choreography spanning Classical, Western, Contemporary, and Hip-Hop on grand festival mainstage.',
      shortDescription: 'Electrifying dance battle across Classical, Folk, and Western genres.',
      rules: '1. Time limit: 4-6 minutes.\n2. Audio tracks must be submitted in MP3 format 2 hours before event.\n3. Evaluated on rhythm, choreography, expressions, and stage presence.',
      eligibility: 'Registered college students.',
      date: 'October 16, 2026',
      startTime: '05:00 PM',
      endTime: '09:00 PM',
      venue: 'Open Air Amphitheatre Main Stage',
      prizePool: '₹35,000',
      firstPrize: '₹22,000 + Dance Idol Trophy',
      secondPrize: '₹13,000 + Memento',
      capacity: 30,
      registeredCount: 18,
      participantType: 'TEAM',
      minTeamSize: 1,
      maxTeamSize: 10,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=80'
    },
    {
      title: 'Voice of COLORIDO (Singing)',
      slug: 'singing',
      category: 'CULTURAL',
      visualType: 'singing',
      description: 'Vocal music competition showcasing melody, vocal range, and musicality across Indian Classical, Light Music, and Western Pop.',
      shortDescription: 'Solo and acoustic vocal music competition with live accompaniment.',
      rules: '1. Time limit: 4 minutes.\n2. Maximum 2 acoustic instruments or one karaoke track allowed.\n3. Vulgarity or offensive lyrics strictly prohibited.',
      eligibility: 'All collegiate singers.',
      date: 'October 15, 2026',
      startTime: '02:00 PM',
      endTime: '06:00 PM',
      venue: 'Silver Jubilee Auditorium',
      prizePool: '₹25,000',
      firstPrize: '₹15,000 + Golden Mic Trophy',
      secondPrize: '₹10,000 + Certificate of Honor',
      capacity: 35,
      registeredCount: 20,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&q=80'
    },
    {
      title: 'Solo Performance',
      slug: 'solo-performance',
      category: 'CULTURAL',
      visualType: 'soloperformance',
      description: 'Individual spotlights in instrumental solos, beatboxing, mime, stand-up comedy, and mono-acting.',
      shortDescription: 'Stage spotlight for individual instrumentalists, comics, and performers.',
      rules: '1. Performance time: 5 minutes.\n2. Original content preferred.\n3. Own instruments must be brought by performers.',
      eligibility: 'Individual college students.',
      date: 'October 15, 2026',
      startTime: '11:00 AM',
      endTime: '03:00 PM',
      venue: 'Mini Auditorium (Block IV)',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Trophy',
      secondPrize: '₹8,000 + Memento',
      capacity: 25,
      registeredCount: 12,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80'
    },
    {
      title: 'Group Performance & Battle of the Bands',
      slug: 'group-performance',
      category: 'CULTURAL',
      visualType: 'groupperformance',
      description: 'High-voltage live rock bands, instrumental fusions, and group orchestral performances with stadium sound systems.',
      shortDescription: 'Collegiate rock band battle and musical ensemble showcase.',
      rules: '1. Total slot: 15 minutes (including 5 min sound check).\n2. Standard drum kit and guitar amps provided on stage.',
      eligibility: 'College band members with student credentials.',
      date: 'October 16, 2026',
      startTime: '06:30 PM',
      endTime: '10:00 PM',
      venue: 'Central Open Ground Main Arena',
      prizePool: '₹40,000',
      firstPrize: '₹25,000 + Best Band Trophy',
      secondPrize: '₹15,000 + Audio Equipment Voucher',
      capacity: 15,
      registeredCount: 8,
      participantType: 'TEAM',
      minTeamSize: 3,
      maxTeamSize: 8,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&q=80'
    },
    {
      title: 'Drama & Theatrical Acts',
      slug: 'drama',
      category: 'CULTURAL',
      visualType: 'drama',
      description: 'Stage plays, skits, street plays (Nukkad Natak), and dramatic enactments depicting compelling social narratives.',
      shortDescription: 'One-act stage plays and dramatic street theater skits.',
      rules: '1. Duration: 10 to 15 minutes.\n2. Minimal props allowed with quick 2-minute setup.\n3. Script summary must be provided to judges beforehand.',
      eligibility: 'Student drama clubs and theatre societies.',
      date: 'October 16, 2026',
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      venue: 'Silver Jubilee Auditorium',
      prizePool: '₹30,000',
      firstPrize: '₹20,000 + Thespian Trophy',
      secondPrize: '₹10,000 + Certificates',
      capacity: 15,
      registeredCount: 7,
      participantType: 'TEAM',
      minTeamSize: 4,
      maxTeamSize: 12,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&q=80'
    },
    {
      title: 'Fashion Show: Runway Couture',
      slug: 'fashion-show',
      category: 'CULTURAL',
      visualType: 'fashionshow',
      description: 'Glamour, haute couture, sustainable fashion, and heritage handloom runway showcase with theme-driven music and walk choreography.',
      shortDescription: 'Themed fashion walk highlighting traditional weaves and futuristic couture.',
      rules: '1. Time limit: 8-10 minutes per team on the ramp.\n2. Themes: Indo-Western Fusion, Sustainable Weaves, or Cyberpunk 2050.\n3. Decency and aesthetic standards must be maintained.',
      eligibility: 'Collegiate styling and modelling teams.',
      date: 'October 17, 2026',
      startTime: '07:30 PM',
      endTime: '09:30 PM',
      venue: 'Open Air Amphitheatre',
      prizePool: '₹35,000',
      firstPrize: '₹22,000 + Runway Champions Cup',
      secondPrize: '₹13,000 + Memento',
      capacity: 12,
      registeredCount: 6,
      participantType: 'TEAM',
      minTeamSize: 6,
      maxTeamSize: 14,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80'
    },
    {
      title: 'Photography: Shutter Speed',
      slug: 'photography',
      category: 'CULTURAL',
      visualType: 'photography',
      description: 'On-the-spot thematic photography capturing vibrant festival moments, candid emotions, architectural symmetry, and dynamic motion.',
      shortDescription: 'Live photography contest capturing festival life and candid frames.',
      rules: '1. Theme announced at 09:00 AM on event day.\n2. RAW or uncompressed JPEG files must be submitted before 03:00 PM.\n3. Basic color correction allowed; generative AI/compositing prohibited.',
      eligibility: 'Student photographers with DSLR/Mirrorless/Smartphone.',
      date: 'October 15, 2026',
      startTime: '09:00 AM',
      endTime: '04:00 PM',
      venue: 'Campus-wide & Media Room Lab',
      prizePool: '₹15,000',
      firstPrize: '₹10,000 + Camera Accessories Kit',
      secondPrize: '₹5,000 + Certificate of Merit',
      capacity: 50,
      registeredCount: 26,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80'
    },
    {
      title: 'Painting & Fine Arts',
      slug: 'painting',
      category: 'CULTURAL',
      visualType: 'painting',
      description: 'Canvas painting, watercolor, charcoal sketching, and creative illustration celebrating vibrant cultural motifs.',
      shortDescription: 'Thematic live canvas painting and fine art showcase.',
      rules: '1. Duration: 2.5 hours.\n2. Drawing sheets and standard easels provided; bring own paints/brushes.\n3. Theme revealed at start of competition.',
      eligibility: 'All collegiate student artists.',
      date: 'October 15, 2026',
      startTime: '10:00 AM',
      endTime: '01:00 PM',
      venue: 'Fine Arts Studio & Courtyard',
      prizePool: '₹15,000',
      firstPrize: '₹9,000 + Artist Art Kit',
      secondPrize: '₹6,000 + Certificate',
      capacity: 40,
      registeredCount: 19,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80'
    },
    {
      title: 'General Knowledge & Pop Culture Quiz',
      slug: 'quiz',
      category: 'CULTURAL',
      visualType: 'quiz',
      description: 'Engaging multi-round collegiate quiz covering World History, Cinema, Sports, Pop Culture, and Literature with buzzer rounds.',
      shortDescription: 'Multi-round general knowledge and pop culture collegiate quiz.',
      rules: '1. Teams of 2.\n2. Written prelims round followed by top 6 teams on stage for audio-visual and buzzer rounds.\n3. Quizmaster verdict is final.',
      eligibility: 'Teams of two college students.',
      date: 'October 16, 2026',
      startTime: '01:30 PM',
      endTime: '05:00 PM',
      venue: 'Mechanical Seminar Hall',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Quiz Whiz Trophy',
      secondPrize: '₹8,000 + Books & Medals',
      capacity: 40,
      registeredCount: 24,
      participantType: 'TEAM',
      minTeamSize: 2,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800&q=80'
    },
    {
      title: 'Literary Events & Debate',
      slug: 'literary-events',
      category: 'CULTURAL',
      visualType: 'literary',
      description: 'Eloquent parliamentary debates, creative poetry slams, and extempore speaking celebrating the power of words and rhetoric.',
      shortDescription: 'Parliamentary debate, poetry slam, and extempore oration.',
      rules: '1. Parliamentary debate 3v3 format.\n2. 5 minutes constructive speech, 2 minutes rebuttal.\n3. Evaluated on argumentation, rhetoric, and rebuttals.',
      eligibility: 'Bonafide college debaters and orators.',
      date: 'October 15, 2026',
      startTime: '10:00 AM',
      endTime: '03:00 PM',
      venue: 'E-Classroom Hall C',
      prizePool: '₹18,000',
      firstPrize: '₹11,000 + Orator Trophy',
      secondPrize: '₹7,000 + Books & Memento',
      capacity: 30,
      registeredCount: 14,
      participantType: 'TEAM',
      minTeamSize: 1,
      maxTeamSize: 3,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&q=80'
    },

    // ==========================================
    // 10 TECHNICAL EVENTS (Section 23)
    // ==========================================
    {
      title: 'Hackathon 24H',
      slug: 'hackathon',
      category: 'TECHNICAL',
      visualType: 'hackathon',
      description: 'The premier 24-hour continuous prototyping sprint of COLORIDO 2K26. Teams conceive, build, and deploy production MVPs tackling AI, FinTech, Sustainability, and Healthcare.',
      shortDescription: '24-hour non-stop prototyping sprint building production apps & AI solutions.',
      rules: '1. Teams of 2 to 4 students.\n2. All code written during hackathon window with verified Git commit history.\n3. Open-source packages allowed; pre-built apps disqualified.\n4. Pitch round before industry judges.',
      eligibility: 'B.Tech/BE/MCA/BCA/Degree students with valid college ID.',
      date: 'October 15-16, 2026',
      startTime: '10:00 AM (Day 1)',
      endTime: '10:00 AM (Day 2)',
      venue: 'High Performance Computing Labs 1-4',
      prizePool: '₹1,00,000',
      firstPrize: '₹50,000 + Championship Trophy',
      secondPrize: '₹30,000 + Runners Plaque',
      capacity: 40,
      registeredCount: 32,
      participantType: 'TEAM',
      minTeamSize: 2,
      maxTeamSize: 4,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80'
    },
    {
      title: 'Coding Contest',
      slug: 'coding-contest',
      category: 'TECHNICAL',
      visualType: 'coding',
      description: 'Algorithmic battle royale testing problem solving, graph algorithms, dynamic programming, and computational complexity on automated test runners.',
      shortDescription: 'Speed algorithmic programming contest on real-time test platforms.',
      rules: '1. Individual participation.\n2. Allowed languages: C++, Java, Python, Go.\n3. 6 algorithmic problems across progressive difficulties.\n4. Plagiarism checks run through MOSS.',
      eligibility: 'Open to all college students.',
      date: 'October 15, 2026',
      startTime: '02:00 PM',
      endTime: '04:30 PM',
      venue: 'CSE Department Advanced Programming Lab',
      prizePool: '₹30,000',
      firstPrize: '₹18,000 + Gold Medal',
      secondPrize: '₹12,000 + Silver Medal',
      capacity: 80,
      registeredCount: 52,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80'
    },
    {
      title: 'Debugging Contest',
      slug: 'debugging-contest',
      category: 'TECHNICAL',
      visualType: 'debugging',
      description: 'Race against time to track down memory leaks, off-by-one errors, concurrency race conditions, and syntactical bugs across legacy codebases.',
      shortDescription: 'Find and fix hidden runtime errors, memory leaks, and logic bugs.',
      rules: '1. Individual event, 90 minutes duration.\n2. Three rounds: Syntax bugs, Memory/Pointer leaks, Logic traps.\n3. Points awarded based on test cases passed and speed of patch submission.',
      eligibility: 'All collegiate student programmers.',
      date: 'October 16, 2026',
      startTime: '10:30 AM',
      endTime: '12:00 PM',
      venue: 'IT Software Engineering Lab',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Bug Hunter Trophy',
      secondPrize: '₹8,000 + Certificate of Merit',
      capacity: 60,
      registeredCount: 38,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 1,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80'
    },
    {
      title: 'Tech Quiz',
      slug: 'tech-quiz',
      category: 'TECHNICAL',
      visualType: 'techquiz',
      description: 'Fast-paced technical trivia testing knowledge across Computer Architecture, Operating Systems, AI models, Cyber Security, Tech History, and Cloud ecosystems.',
      shortDescription: 'Brain-churning tech trivia, architecture questions, and buzzer rounds.',
      rules: '1. Teams of 2.\n2. Round 1: Rapid 30-question MCQ screening.\n3. Round 2: On-stage buzzer, visual identify, and reverse code rounds.',
      eligibility: 'Undergraduate and postgraduate technology students.',
      date: 'October 15, 2026',
      startTime: '11:00 AM',
      endTime: '01:00 PM',
      venue: 'ECE Department Seminar Hall',
      prizePool: '₹20,000',
      firstPrize: '₹12,000 + Tech Master Shield',
      secondPrize: '₹8,000 + Books',
      capacity: 50,
      registeredCount: 31,
      participantType: 'TEAM',
      minTeamSize: 2,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80'
    },
    {
      title: 'Paper Presentation',
      slug: 'paper-presentation',
      category: 'TECHNICAL',
      visualType: 'paper',
      description: 'Symposium for emerging academic research in IEEE format across Machine Learning, IoT, Clean Energy, VLSI, and Quantum Computing judged by professors.',
      shortDescription: 'Present IEEE-standard original research papers before faculty jury.',
      rules: '1. IEEE double-column 4-6 pages format.\n2. Presentation: 10 minutes slide deck + 3 minutes Q&A.\n3. Plagiarism strictly below 15%.',
      eligibility: 'Bonafide UG/PG engineering students.',
      date: 'October 16, 2026',
      startTime: '09:30 AM',
      endTime: '01:30 PM',
      venue: 'Silver Jubilee Conference Room',
      prizePool: '₹25,000',
      firstPrize: '₹15,000 + Best Paper Award',
      secondPrize: '₹10,000 + Memento',
      capacity: 35,
      registeredCount: 21,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80'
    },
    {
      title: 'Project Expo',
      slug: 'project-expo',
      category: 'TECHNICAL',
      visualType: 'projectexpo',
      description: 'Exhibition of working hardware prototypes, IoT devices, robotics systems, embedded automation, and patent-pending innovations with live visitor demos.',
      shortDescription: 'Live working exhibition of hardware prototypes, robotics, and IoT systems.',
      rules: '1. Teams of 2 to 4.\n2. Working physical prototype or live hardware test bench mandatory.\n3. Poster board (3x2 ft) explaining architecture and circuit design required.',
      eligibility: 'Engineering and Polytechnic students.',
      date: 'October 16, 2026',
      startTime: '10:00 AM',
      endTime: '04:00 PM',
      venue: 'Central Innovation & Incubation Center',
      prizePool: '₹35,000',
      firstPrize: '₹20,000 + Innovator Trophy',
      secondPrize: '₹15,000 + Seed Grant Shield',
      capacity: 30,
      registeredCount: 19,
      participantType: 'TEAM',
      minTeamSize: 2,
      maxTeamSize: 4,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80'
    },
    {
      title: 'UI/UX Design Challenge',
      slug: 'ui-ux-design-challenge',
      category: 'TECHNICAL',
      visualType: 'uiux',
      description: 'Rapid design sprint crafting interactive Figma wireframes, design systems, and micro-interactions for a real-world product problem statement.',
      shortDescription: 'Design sprint creating responsive prototypes and Figma design systems.',
      rules: '1. Problem statement revealed at start of sprint.\n2. 3 hours duration in Figma/Penpot.\n3. Submission must include user journey, wireframe, high-fidelity mockups, and interactive prototype.',
      eligibility: 'Design enthusiasts and frontend students.',
      date: 'October 15, 2026',
      startTime: '01:30 PM',
      endTime: '04:30 PM',
      venue: 'Design & Multimedia Studio (Block III)',
      prizePool: '₹25,000',
      firstPrize: '₹15,000 + UI Designer Trophy',
      secondPrize: '₹10,000 + Figma Subscriptions',
      capacity: 40,
      registeredCount: 25,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1581291518655-9523c932dede?w=800&q=80'
    },
    {
      title: 'Web Development Challenge',
      slug: 'web-development-challenge',
      category: 'TECHNICAL',
      visualType: 'webdev',
      description: 'Full-stack time-attack sprint: build a functional, responsive web application from a prompt with API integrations, state management, and modern CSS.',
      shortDescription: 'Fast-paced sprint building full-stack web applications with modern frameworks.',
      rules: '1. Time limit: 3.5 hours.\n2. Tech stack: React, Vue, Next.js, Node.js, Tailwind CSS.\n3. App must be deployed live with accessible URL for judge evaluation.',
      eligibility: 'Student web developers.',
      date: 'October 16, 2026',
      startTime: '01:00 PM',
      endTime: '04:30 PM',
      venue: 'Web Technologies Lab 2',
      prizePool: '₹30,000',
      firstPrize: '₹18,000 + Webmaster Trophy',
      secondPrize: '₹12,000 + Domain & Hosting Bundles',
      capacity: 45,
      registeredCount: 30,
      participantType: 'INDIVIDUAL',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80'
    },
    {
      title: 'AI/ML Challenge',
      slug: 'ai-ml-challenge',
      category: 'TECHNICAL',
      visualType: 'aiml',
      description: 'Kaggle-style machine learning competition: clean noisy data, engineer features, train neural networks, and deploy inference pipelines on blind test sets.',
      shortDescription: 'Train, tune, and submit deep learning and ML models under strict GPU constraints.',
      rules: '1. Teams of 1-2 students.\n2. Submissions evaluated on F1-score/RMSE against private benchmark test split.\n3. Code reproducibility check mandatory.',
      eligibility: 'Knowledge of Python, Scikit-Learn, PyTorch, or TensorFlow.',
      date: 'October 15, 2026',
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      venue: 'Center of Excellence for Artificial Intelligence',
      prizePool: '₹35,000',
      firstPrize: '₹20,000 + AI Innovator Trophy',
      secondPrize: '₹15,000 + Edge AI Kit',
      capacity: 40,
      registeredCount: 27,
      participantType: 'TEAM',
      minTeamSize: 1,
      maxTeamSize: 2,
      featured: true,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80'
    },
    {
      title: 'Code Relay',
      slug: 'code-relay',
      category: 'TECHNICAL',
      visualType: 'coderelay',
      description: 'Thrilling team coding relay! Teammates take turns coding in 10-minute relay handoffs without vocal communication, building upon teammate logic.',
      shortDescription: 'Team coding relay race with 10-minute rotation shifts and zero verbal communication.',
      rules: '1. Teams of 3 developers.\n2. Relay rotation every 10 minutes; returning coder cannot speak.\n3. Clean comments and modular code essential for handoff score.',
      eligibility: 'Teams of 3 students.',
      date: 'October 17, 2026',
      startTime: '02:30 PM',
      endTime: '05:00 PM',
      venue: 'Systems Programming Lab 1',
      prizePool: '₹25,000',
      firstPrize: '₹15,000 + Relay Champions Trophy',
      secondPrize: '₹10,000 + Mechanical Keyboards',
      capacity: 25,
      registeredCount: 16,
      participantType: 'TEAM',
      minTeamSize: 3,
      maxTeamSize: 3,
      featured: false,
      published: true,
      imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80'
    }
  ];

  const createdEvents = [];
  for (const ev of events) {
    const created = await prisma.event.create({ data: ev });
    createdEvents.push(created);
  }
  console.log(`✓ Seeded ${createdEvents.length} Events (9 Sports, 10 Cultural, 10 Technical)`);

  const eventMap = {};
  createdEvents.forEach(e => {
    eventMap[e.visualType] = e;
  });

  // 3. SEED SCHEDULE (Section 60)
  const schedules = [
    // Day 1 (October 15, 2026)
    {
      title: 'National 24H Hackathon Kickoff',
      category: 'TECHNICAL',
      date: '2026-10-15',
      startTime: '10:00 AM',
      endTime: '12:00 PM',
      venue: 'High Performance Computing Labs',
      stage: 'Track 1',
      description: 'Problem statement release and mentorship orientation.',
      status: 'SCHEDULED',
      published: true,
      order: 1,
      eventId: eventMap['hackathon']?.id
    },
    {
      title: 'Cricket Prelims Round 1',
      category: 'SPORTS',
      date: '2026-10-15',
      startTime: '08:30 AM',
      endTime: '12:30 PM',
      venue: 'Main Cricket Ground',
      stage: 'Pitch 1',
      description: 'Knockout matches between collegiate teams.',
      status: 'SCHEDULED',
      published: true,
      order: 2,
      eventId: eventMap['cricket']?.id
    },
    {
      title: 'Voice of COLORIDO Prelims',
      category: 'CULTURAL',
      date: '2026-10-15',
      startTime: '02:00 PM',
      endTime: '06:00 PM',
      venue: 'Silver Jubilee Auditorium',
      stage: 'Main Stage',
      description: 'Solo vocal auditions and light music performances.',
      status: 'SCHEDULED',
      published: true,
      order: 3,
      eventId: eventMap['singing']?.id
    },
    {
      title: 'AI/ML Model Training Round',
      category: 'TECHNICAL',
      date: '2026-10-15',
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      venue: 'AI Center of Excellence',
      stage: 'Lab 2',
      description: 'Kaggle style blind test inference sprint.',
      status: 'SCHEDULED',
      published: true,
      order: 4,
      eventId: eventMap['aiml']?.id
    },
    {
      title: 'Grandmaster Chess Round 1-3',
      category: 'SPORTS',
      date: '2026-10-15',
      startTime: '10:00 AM',
      endTime: '01:30 PM',
      venue: 'Student Activity Center Hall A',
      stage: 'Tables 1-20',
      description: 'Swiss-system rapid chess matches.',
      status: 'SCHEDULED',
      published: true,
      order: 5,
      eventId: eventMap['chess']?.id
    },
    // Day 2 (October 16, 2026)
    {
      title: 'Hackathon Grand Jury Pitches',
      category: 'TECHNICAL',
      date: '2026-10-16',
      startTime: '10:00 AM',
      endTime: '01:00 PM',
      venue: 'Main Auditorium',
      stage: 'Podium',
      description: 'Final 10 teams pitch working solutions to tech leaders.',
      status: 'SCHEDULED',
      published: true,
      order: 6,
      eventId: eventMap['hackathon']?.id
    },
    {
      title: 'Dance Fiesta Showcase',
      category: 'CULTURAL',
      date: '2026-10-16',
      startTime: '05:00 PM',
      endTime: '09:00 PM',
      venue: 'Open Air Amphitheatre',
      stage: 'Central Stage',
      description: 'Classical, western, and hip-hop group dance finals.',
      status: 'SCHEDULED',
      published: true,
      order: 7,
      eventId: eventMap['dance']?.id
    },
    {
      title: 'Football Champions Cup Finals',
      category: 'SPORTS',
      date: '2026-10-16',
      startTime: '03:30 PM',
      endTime: '05:30 PM',
      venue: 'South Stadium Football Arena',
      stage: 'Main Turf',
      description: 'Grand final match under floodlights.',
      status: 'SCHEDULED',
      published: true,
      order: 8,
      eventId: eventMap['football']?.id
    },
    // Day 3 (October 17, 2026)
    {
      title: 'Fashion Show: Runway Couture',
      category: 'CULTURAL',
      date: '2026-10-17',
      startTime: '07:30 PM',
      endTime: '09:30 PM',
      venue: 'Open Air Amphitheatre',
      stage: 'Ramp',
      description: 'Heritage handloom and fusion runway exhibition.',
      status: 'SCHEDULED',
      published: true,
      order: 9,
      eventId: eventMap['fashionshow']?.id
    },
    {
      title: 'Code Relay Championship',
      category: 'TECHNICAL',
      date: '2026-10-17',
      startTime: '02:30 PM',
      endTime: '05:00 PM',
      venue: 'Systems Programming Lab 1',
      stage: 'Arena',
      description: 'Thrilling 10-minute rotation team coding relay.',
      status: 'SCHEDULED',
      published: true,
      order: 10,
      eventId: eventMap['coderelay']?.id
    }
  ];

  for (const s of schedules) {
    await prisma.schedule.create({ data: s });
  }
  console.log(`✓ Seeded ${schedules.length} Schedule events`);

  // 4. SEED SAMPLE RESULTS (Section 61)
  const results = [
    {
      eventId: eventMap['hackathon'].id,
      category: 'TECHNICAL',
      rank: 1,
      position: '1st Place (Gold)',
      participantName: 'Team NeuralByte',
      college: 'R V R & J C College of Engineering',
      teamName: 'NeuralByte',
      score: '96.5/100',
      notes: 'Autonomous multi-modal drone assistance system with local edge LLM.',
      published: true
    },
    {
      eventId: eventMap['hackathon'].id,
      category: 'TECHNICAL',
      rank: 2,
      position: '2nd Place (Silver)',
      participantName: 'Team Algorists',
      college: 'VR Siddhartha Engineering College',
      teamName: 'Algorists',
      score: '93.0/100',
      notes: 'Decentralized medical records verification with zero-knowledge proofs.',
      published: true
    },
    {
      eventId: eventMap['cricket'].id,
      category: 'SPORTS',
      rank: 1,
      position: '1st Place (Gold)',
      participantName: 'RVRJC Titans Cricket XI',
      college: 'R V R & J C College of Engineering',
      teamName: 'RVRJC Titans',
      score: '178/4 (18.2 ov) vs 175/7',
      notes: 'Won by 6 wickets in a thrilling final over finish.',
      published: true
    },
    {
      eventId: eventMap['cricket'].id,
      category: 'SPORTS',
      rank: 2,
      position: '2nd Place (Silver)',
      participantName: 'Andhra Loyola Lions',
      college: 'Andhra Loyola College',
      teamName: 'Loyola Lions',
      score: '175/7 (20 ov)',
      notes: 'Runners up with spirited tournament campaign.',
      published: true
    },
    {
      eventId: eventMap['dance'].id,
      category: 'CULTURAL',
      rank: 1,
      position: '1st Place (Gold)',
      participantName: 'Step Up Crew',
      college: 'KL University',
      teamName: 'Step Up Crew',
      score: '98/100',
      notes: 'Incredible lyrical hip-hop sync with acrobatic flips.',
      published: true
    },
    {
      eventId: eventMap['dance'].id,
      category: 'CULTURAL',
      rank: 2,
      position: '2nd Place (Silver)',
      participantName: 'Nritya Tarang Classical Troupe',
      college: 'R V R & J C College of Engineering',
      teamName: 'Nritya Tarang',
      score: '95/100',
      notes: 'Mesmerizing Kuchipudi and Bharatanatyam fusion.',
      published: true
    },
    {
      eventId: eventMap['coding'].id,
      category: 'TECHNICAL',
      rank: 1,
      position: '1st Place (Gold)',
      participantName: 'K. V. Sai Krishna',
      college: 'R V R & J C College of Engineering',
      teamName: 'Solo',
      score: '600/600 (42m penalty)',
      notes: 'Solved all 6 dynamic programming and graph problems in 42 minutes.',
      published: true
    },
    {
      eventId: eventMap['chess'].id,
      category: 'SPORTS',
      rank: 1,
      position: '1st Place (Gold)',
      participantName: 'M. Rohit Varma',
      college: 'Guntur Medical College',
      teamName: 'Solo',
      score: '5.5 / 6.0 Pts',
      notes: 'Undefeated in Swiss-system rapid chess championship.',
      published: true
    }
  ];

  for (const r of results) {
    await prisma.result.create({ data: r });
  }
  console.log(`✓ Seeded ${results.length} Results`);

  // 5. SEED CONTACT MESSAGES
  const messages = [
    {
      name: 'Dr. P. Sudhakar',
      email: 'sudhakar.hod@gvpce.ac.in',
      phone: '+91 98480 11223',
      subject: 'Inquiry regarding 24H Hackathon Hardware Kits',
      message: 'Hello COLORIDO team, our college is sending 3 teams for the 24H Hackathon. Will 230V power sockets and oscilloscopes be provided at the desks?',
      status: 'UNREAD'
    },
    {
      name: 'Sneha Reddy',
      email: 'snehareddy@gmail.com',
      phone: '+91 97000 44556',
      subject: 'Accommodation query for Dance Fiesta participants',
      message: 'Hi, we are coming from Visakhapatnam for the cultural events. Can you confirm if hostel accommodation is available on campus on October 15 and 16?',
      status: 'READ'
    }
  ];

  for (const m of messages) {
    await prisma.contactMessage.create({ data: m });
  }
  console.log(`✓ Seeded ${messages.length} Contact Messages`);

  console.log('--- COLORIDO 2K26 SEED COMPLETED SUCCESSFULLY ---');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
